# Generated by Django 3.0.5 on 2024-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.IntegerField()),
                ('assessment_number', models.IntegerField()),
                ('door_number', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('relative_name', models.CharField(max_length=255)),
                ('house_tax', models.FloatField()),
                ('library_cess', models.FloatField()),
                ('water_tax', models.FloatField()),
                ('lightning_tax', models.FloatField()),
                ('fire_tax', models.FloatField()),
                ('sports_cess', models.FloatField()),
                ('drainage_tax', models.FloatField()),
                ('total_current_year_tax', models.FloatField()),
                ('arrear_tax', models.FloatField()),
                ('total_tax', models.FloatField()),
                ('cluster_number', models.IntegerField()),
                ('payment', models.BooleanField()),
            ],
        ),
    ]
